# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-20 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlacierBackup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('glacier_id', models.CharField(max_length=138, unique=True, verbose_name=b'Glacier backup ID')),
                ('date', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Glacier backup',
                'verbose_name_plural': 'Glacier backups',
            },
        ),
        migrations.CreateModel(
            name='GlacierInventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_id', models.CharField(max_length=92, unique=True, verbose_name=b'Glacier inventory ID')),
                ('collected_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('requested_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
